---
# Interface to configure
static_ip_interface: "eth0"

# State of the configuration (present/absent)
static_ip_state: "present"

# Default DNS (Google DNS)
static_ip_dns: "8.8.8.8"

# Whether to configure Dropbear (initramfs) IP as well
configure_dropbear_ip: true

# Path to cmdline.txt (configurable for testing)
static_ip_cmdline_path: "/boot/firmware/cmdline.txt"
